server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中对应
        tx-service-group: my_test_tx_service #因为seata的file.config文件没有service模块，事务组名默认为my_test_service
        #service要与tx-service-group对齐，vgroupMapping和grouplist再service的下一级
        service:
          vgroupMapping:
            my_test_service: default
          grouplist:
            default: 10.0.41.31:8091
    nacos:
      discovery:
        server-addr: 10.0.41.31:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage?useUnicode=true&charset=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
feign:
  hystrix:
    enabled: true
logging:
  level:
    io:
      seata: info
mybatis:
  mapper-locations: classpath*:mapper/*.xml

