server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #nacos服务注册中心地址
        server-addr: 10.0.41.31:8848
    sentinel:
      transport:
        #配置Sentinel dashboard 地址
        dashboard: localhost:8080
        # 默认8719端口 假设被占用了 会自动冲8719+1，直到找到未被占用的端口
        port: 8719
        clientIp: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
debug: true