server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cl.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&charset=utf-8&useSSL=true
    username: root
    password: root

mybaits:
  mapper-location: classpath:mapper/*.xml
  type-aliases-package: com.xiaotu.spring.entities
