server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 10.0.41.31
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: studyExchange
          content: application/json
          binder: defaultRabbit
          group: xiaotuA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: receive-8002.com
    prefer-ip-address: true