server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      label: main #读取分支
      server:
        git:
          search-paths:
            - cloud-config
          uri: https://github.com/cuixiaotu/cloud-config.git
          username: 616364596@qq.com
          password: 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
          default-label: main
  rabbitmq:
    host: 10.0.41.31
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:7001/eureka
debug: true
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'